### PR TITLE
Remove IOException from source() and streams.

### LINKED ISSUE #1696: Evaluate removing IOException from ResponseBody close
Propagating the already-rare exception that can be thrown when closing the underlying `Source` of a `ResponseBody` is not actionable and puts the caller in an awkward position. Is there any use to this exception? Or should we simply swallow it for the caller's convenience since it's what they are going to do anyway?

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #1696.

### CODE REVIEW

File: okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java [hunk 1]
```diff
@@ -727,7 +718,11 @@ public Object getContent(Class[] classes) throws IOException {
 
     @Override
     public InputStream getInputStream() throws IOException {
-      throw throwResponseBodyAccessException();
+      return new InputStream() {
+        @Override public int read() throws IOException {
+          throw throwResponseBodyAccessException();
```
Comment (JakeWharton) [inline okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java]: I'm most unsure about the changes in this file because the larger semantics of this are unclear to me. As you can see, this is the _only_ usage which necessitated the `throws IOException` declaration. Nothing in OkHttp core needs it.

Comment (swankjesse) [inline okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java]: Let’s change this to be an UnsupportedOperationException?

Comment (swankjesse) [inline okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java]: ... it already is!

File: okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java [hunk 2]
```diff
@@ -1866,8 +1866,9 @@ private void assertGatewayTimeout(HttpURLConnection connection) throws IOExcepti
         HttpURLConnection httpURLConnection = (HttpURLConnection) connection;
         assertEquals(server.url("/").url(), uri.toURL());
         assertEquals(200, httpURLConnection.getResponseCode());
+        InputStream is = httpURLConnection.getInputStream();
         try {
-          httpURLConnection.getInputStream();
```
Comment (swankjesse) [inline okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java]: I think this might have just worked?

Comment (JakeWharton) [inline okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java]: It failed on `fail()` without.

Comment (swankjesse) [inline okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java]: what about just having `getInputStream` throw UOE ?

Comment (JakeWharton) [inline okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java]: That fails 100s of tests since it is now eagerly opened above. The alternative is a `Source` that lazily opens the underlying `InputStream` on first access and then forwards all calls.

File: okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java (hunk 1 above)
Comment (swankjesse) [inline okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java]: Got it. It’s because now `createOkBody` delegates here.

**Comment by swankjesse** [comment]
So eager to nuke the twisty maze of HttpURLConnection support.
