### PR TITLE
Break apart close states. Try to send close on IOE.

### LINKED ISSUE #1931: IOException when writing to Websocket sink causes writing to fail forever
This change: [https://github.com/square/okhttp/commit/40a6dc7dd5ff6843b82f904516181182d512d0ca] contains these lines in `public void sendMessage(RequestBody message)`:

```java 
    BufferedSink sink = Okio.buffer(writer.newMessageSink(formatOpcode));
    message.writeTo(sink);
    sink.close();
```

Perhaps rephrase as:
```java
    BufferedSink sink = Okio.buffer(writer.newMessageSink(formatOpcode));
    try {
      message.writeTo(sink);
    } finally {
      sink.close();
    }
```

If an `IOException` is thrown here the sink will never close yet the websocket will remain in a valid state. This causes subsequent executions of `writer.NewMessageSink(formatOpcode)` to fail because the writer is still active.

### PR DESCRIPTION
**Pull request by JakeWharton**
This breaks apart the states used to track sending a close message and whether or not the connection has been closed. Prior to this, certain threading orders would allow multiple calls to close() which would attempt to remove ownership of the connection, the second of which would fail.

Closes #1931.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Sorry there's a lot here. I can probably split it into two PRs if that helps.

File: okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java [hunk 1]
```diff
@@ -46,8 +47,9 @@
   private volatile boolean writerSentClose;
```
Comment (JakeWharton) [inline okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java]: This no longer requires locking. Only the application thread reads and writes to it for deciding whether to throw an `IllegalStateException`. Other threads look at the value as an indicator of whether they should try to write a close frame, but they'll ultimately catch the `IOException` if they end up missing the correct value.

File: okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java [hunk 2]
```diff
@@ -45,9 +46,10 @@
   /** True after calling {@link #close(int, String)}. No writes are allowed afterward. */
   private volatile boolean writerSentClose;
   /** True after a close frame was read by the reader. No frames will follow it. */
-  private volatile boolean readerSentClose;
-  /** Lock required to negotiate closing the connection. */
-  private final Object closeLock = new Object();
+  private boolean readerSentClose;
```
Comment (JakeWharton) [inline okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java]: This no longer requires locking or even `volatile`. It's value is only read and written on the reader thread.

File: okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java [hunk 3]
```diff
@@ -207,7 +219,92 @@
...
+      fail();
+    } catch (IOException e) {
+      assertSame(brokenException, e);
+    }
+
+    // A failed write prevents further use of the WebSocket instance.
+    try {
+      client.sendPing(new Buffer().writeUtf8("Ping!"));
+      fail();
+    } catch (IllegalStateException e) {
```
Comment (swankjesse) [inline okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java]: not sure I like the consequences here. One client throwing an IOException can cause another client to get a runtime exception?

Comment (swankjesse) [inline okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java]: ... I think the only defensible exception here is another IOException, perhaps `IOException("stream not writable")`

Comment (swankjesse) [inline okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java]: ... rule of thumb: if it's a programming bug, IllegalStateException. If it's not, IOException. Here I think it isn't a programming bug.

File: okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java [hunk 4]
```diff
@@ -218,12 +315,26 @@
...
     }
+  }
+
+  @Test public void serverCloseThenWritingCloseThrows() throws IOException {
+    server.close(1000, "Hello!");
+    client.readMessage();
+    clientListener.assertClose(1000, "Hello!");
+
     try {
       client.close(1000, "Bye!");
```
Comment (swankjesse) [inline okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java]: should this just fail silently? I have no idea what the application layer would want

Comment (swankjesse) [inline okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java]: For reference, our framed stuff throws if there's an IOException writing the actual bytes, but silently ignores close on already closed. Looks like this is the same. (And that's as good a policy as any!)

File: okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java (hunk 1 above)
Comment (swankjesse) [inline okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java]: Do multiple threads share a single client socket socket? My guess is that the UI will enqueue messages to be sent asynchronously, so a single write that fails shouldn't cause other writes to be treated as programming errors?

File: okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java (hunk 2 above)
Comment (swankjesse) [inline okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java]: Win.

File: okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java [hunk 5]
```diff
@@ -129,51 +124,77 @@ public boolean readMessage() {
...
-    writer.writeClose(code, reason);
-
-    if (performClose) {
-      close();
+    try {
+      writer.writeClose(code, reason);
+    } catch (IOException e) {
+      if (connectionClosed.compareAndSet(false, true)) {
+        // Try to close the connection without masking the original exception.
+        try {
```
Comment (swankjesse) [inline okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java]: `closeQuietly(this)` ?

Comment (swankjesse) [inline okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java]: nope, not a public method!

**Comment by swankjesse** [comment]
Structure looks good but I'm unhappy with the exceptions. Thoughts?

File: okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java (hunk 3 above)
Comment (JakeWharton) [inline okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java]: There is only one client. If it gets IO then subsequent interactions are a
programming bug.

File: okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java (hunk 1 above)
Comment (JakeWharton) [inline okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java]: Writes are single threaded and serial. If the calling code calls close,
there's no reason for it to interact with the WebSocket again.

Even if writes are queued, a single thread will be processing them and it
will know whether it ever called close or not.

**Comment by swankjesse** [comment]
Merged cause the stuff I'm worried about is a corner case, possibly academic. I serve the right to make a follow up PR!
