### PR TITLE
Force consumers to call WS#close on IO error.

### LINKED ISSUE #1931: IOException when writing to Websocket sink causes writing to fail forever
This change: [https://github.com/square/okhttp/commit/40a6dc7dd5ff6843b82f904516181182d512d0ca] contains these lines in `public void sendMessage(RequestBody message)`:

```java 
    BufferedSink sink = Okio.buffer(writer.newMessageSink(formatOpcode));
    message.writeTo(sink);
    sink.close();
```

Perhaps rephrase as:
```java
    BufferedSink sink = Okio.buffer(writer.newMessageSink(formatOpcode));
    try {
      message.writeTo(sink);
    } finally {
      sink.close();
    }
```

If an `IOException` is thrown here the sink will never close yet the websocket will remain in a valid state. This causes subsequent executions of `writer.NewMessageSink(formatOpcode)` to fail because the writer is still active.

### PR DESCRIPTION
**Pull request by JakeWharton**
This actually un-fixes #1931, but it formalizes the consumer behavior (and ensures that it will behave correctly).

### CODE REVIEW

File: okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java [hunk 1]
```diff
@@ -279,28 +253,16 @@
...
-      client.sendPing(new Buffer().writeUtf8("Ping!"));
+      client.sendMessage(RequestBody.create(TEXT, "Hello!"));
       fail();
     } catch (IllegalStateException e) {
-      assertEquals("closed", e.getMessage());
+      assertEquals("must call close()", e.getMessage());
     }
-  }
-
-  @Test public void socketClosedDuringCloseKillsWebSocket() throws IOException {
```
Comment (JakeWharton) [inline okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java]: This case is already covered above.
