### PR TITLE
Avoid failing on single double quote in JavaNetCookieJar

### LINKED ISSUE #6721: StringIndexOutOfBoundsException at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.kt:98)
I see exceptions in cookie parser. Most likely the cookies are invalid but it's better to handle it w/o throwing errors:

Invalid cookie for https://www1.shoppersdrugmart.ca/en/health-and-pharmacy: Shoppers Drug Mart_Language=en-ca; expires=Tue, 20 Jul 2021 18:57:18 GMT; path=/; secure
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.kt:98)
        at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.kt:59)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:74)

SEVERE: Invalid cookie for https://www.bankofbaroda.in/contact-us.htm: ClassBank Of Baroda CMSs=; path=/; secure; httponly
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.kt:98)

Okhttp gradle dependencies:
    implementation("com.squareup.okhttp3:okhttp:4.9.1")
    implementation("com.squareup.okhttp3:okhttp-dnsoverhttps:5.0.0-alpha.2")
    implementation("com.squareup.okhttp3:okhttp-urlconnection:4.9.1")

### PR DESCRIPTION
**Pull request by yschimke**
Fixes #6721

### CODE REVIEW

File: okhttp-urlconnection/src/main/kotlin/okhttp3/JavaNetCookieJar.kt [hunk 1]
```diff
@@ -94,7 +94,7 @@ class JavaNetCookieJar(private val cookieHandler: CookieHandler) : CookieJar {
       }
 
       // If the value is "quoted", drop the quotes.
-      if (value.startsWith("\"") && value.endsWith("\"")) {
+      if (value.startsWith("\"") && value.endsWith("\"") && value.length >= 2) {
```
Comment (swankjesse) [inline okhttp-urlconnection/src/main/kotlin/okhttp3/JavaNetCookieJar.kt:97]: nice

**Review by swankjesse — APPROVED** [review]
