### PR TITLE
fix: real unmodifiable list

### LINKED ISSUE #8721: Fix immutable list creation
Revert or correct https://github.com/square/okhttp/pull/8719. Its lists are still modifiable from Java with `set`.

### PR DESCRIPTION
**Pull request by MukjepScarlet**
fixes #8721

### CODE REVIEW

**Comment by MukjepScarlet** [comment]
@JakeWharton Please review

**Review by JakeWharton — APPROVED** [review]

File: okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilJvm.kt [hunk 1]
```diff
@@ -233,17 +234,17 @@ internal inline fun threadName(
 }
 
 /** Returns the Content-Length as reported by the response headers. */
-internal fun Response.headersContentLength(): Long = headers["Content-Length"]?.toLongOrDefault(-1L) ?: -1L
+internal fun Response.headersContentLength(): Long = headers["Content-Length"]?.toLongOrNull() ?: -1L
```
Comment (swankjesse) [inline okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilJvm.kt:237]: Why make our code slower?

Here’s the Java equivalent of what we had before (IntelliJ ‘Show Kotlin Bytecode’, followed by ‘Decompile’):

```kotlin
   public static final long headersContentLength(@NotNull Response $this$headersContentLength) {
      Intrinsics.checkNotNullParameter($this$headersContentLength, "<this>");
      String var10000 = $this$headersContentLength.headers().get("Content-Length");
      return var10000 != null ? _UtilCommonKt.toLongOrDefault(var10000, -1L) : -1L;
   }
```

and here’s after:

```kotlin
   public static final long headersContentLength(@NotNull Response $this$headersContentLength) {
      Intrinsics.checkNotNullParameter($this$headersContentLength, "<this>");
      String var10000 = $this$headersContentLength.headers().get("Content-Length");
      long var2;
      if (var10000 != null) {
         Long var1 = StringsKt.toLongOrNull(var10000);
         if (var1 != null) {
            var2 = var1;
            return var2;
         }
      }

      var2 = -1L;
      return var2;
   }
```

The old code didn’t allocate, and the new code does.
