### PR TITLE
Correctly calculate HTTP2 response body size

### LINKED ISSUE #4948: HEAD requests break if the response contains the content-length header over HTTP2
This is similar to #2998 except it only happens on HTTP2 requests. The following example with okhttp `3.14.1` shows the issue:

````java
@Test
public void headOverHttp2() throws IOException {
    try (Response resp = client.newCall(
        new Request.Builder()
            .head()
            .url("https://http2.akamai.com/demo")
            .build()
    ).execute()) {
        System.out.println("resp.protocol() = " + resp.protocol().toString());
        System.out.println("resp.header(\"content-length\") = " + resp.header("content-length"));
        System.out.println("resp.body().contentLength() = " + resp.body().contentLength());
        System.out.println("resp.body().bytes().length = " + resp.body().bytes().length);
    }
}
````

I get this output:

	resp.protocol() = h2
	resp.header("content-length") = 2421
	resp.body().contentLength() = 2421

	java.io.IOException: Content-Length (2421) and stream length (0) disagree
		at okhttp3.ResponseBody.bytes(ResponseBody.java:139)

It is `resp.body().bytes().length` that throws the exception. When not using HTTP2, the `resp.body().contentLength()` correctly returns 0, as does `resp.body().bytes().length`.

### PR DESCRIPTION
**Pull request by monkey-mas**
Fixes #4948

Currently response body size is determined by `Content-Length` header value, i.e. we use the header value if it exists, otherwise set -1.

This doesn't work for some HTTP responses. For example, `response.body().contentLength()` should return 0 for a response of HEAD request instead of using the `Content-Length` value. Also it should return 0 for a 204 responses instead of providing -1 when Content-Length header is not present.

### CODE REVIEW

File: okhttp/src/main/java/okhttp3/internal/http2/Http2ExchangeCodec.kt [hunk 1]
```diff
@@ -106,7 +107,10 @@ class Http2ExchangeCodec(
   }
 
   override fun reportedContentLength(response: Response): Long {
-    return response.headersContentLength()
+    return when {
+      !response.promisesBody() -> 0L
+      else -> response.headersContentLength()
+    }
```
Comment (monkey-mas) [inline okhttp/src/main/java/okhttp3/internal/http2/Http2ExchangeCodec.kt]: I think we don't have to handle chunked (Transfer-Encoding) response unlike HTTP1.

https://tools.ietf.org/html/rfc7540#section-8.1 says `HTTP/2 uses DATA frames to carry message payloads. The "chunked" transfer encoding defined in Section 4.1 of [RFC7230] MUST NOT be used in HTTP/2.`

File: okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java [hunk 2]
```diff
@@ -187,6 +187,53 @@ private OkHttpClient buildHttp2Client() {
...
+        .head()
+        .url(server.url("/foo"))
+        .build());
+
+    Response response = call.execute();
+
+    // Body contains nothing.
+    assertThat(response.body().bytes().length).isEqualTo(0);
+    assertThat(response.body().contentLength()).isEqualTo(0);
+
```
Comment (monkey-mas) [inline okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java]: `assertThat(response.body().string()).isEqualTo("");` triggered an exception. Is this expected?
```
java.lang.IllegalStateException: closed

	at okio.RealBufferedSource.select(RealBufferedSource.kt:83)
	at okhttp3.internal.Util.readBomAsCharset(Util.kt:256)
	at okhttp3.ResponseBody.string(ResponseBody.kt:172)
	at okhttp3.internal.http2.HttpOverHttp2Test.head(HttpOverHttp2Test.java:229)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at okhttp3.OkHttpClientTestRule$1.evaluate(OkHttpClientTestRule.java:37)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

File: okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java [hunk 3]
```diff
@@ -187,6 +187,53 @@ private OkHttpClient buildHttp2Client() {
         (server.getHostName() + ":" + server.getPort()));
   }
```
Comment (monkey-mas) [inline okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java]: Can we write other integration/unit tests?

File: okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java (hunk 2 above)
Comment (swankjesse) [reply okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java]: Yep, you can’t request the body multiple times.

**Comment by swankjesse** [comment]
Thanks! Sorry for dropping the ball on this one, it’s a nice improvement!
