### PR TITLE
WebSockets should show an empty body to interceptors.

### LINKED ISSUE #2811: HttpLoggingInterceptor.java maybe occur a NullPointException on line 220;
`Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:220)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.access$100(RealCall.java:33)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)`

`HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor().setLevel(level);
builder.addInterceptor(loggingInterceptor);    // log
OkHttpClient okHttpClient = builder.build();
WebSocketCall call = new WebSocketCall(okHttpClient, request);`

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #2811.

### CODE REVIEW

File: okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java [hunk 1]
```diff
@@ -57,7 +58,13 @@ public CallServerInterceptor(boolean forWebSocket) {
         .receivedResponseAtMillis(System.currentTimeMillis())
         .build();
 
-    if (!forWebSocket || response.code() != 101) {
+    int code = response.code();
+    if (forWebSocket && code == 101) {
```
Comment (swankjesse) [inline okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java]: much neater
